language: node_js

node_js:
  - "lts/*"

services:
  - docker
  - mongodb
  - mysql
  - postgresql
  - couchdb
  - sqlite3
  - redis
  - cassandra
  - elasticsearch
  - rethinkdb

before_install:
  - mysql -e 'CREATE DATABASE etherdb;'
  - mysql -e 'CREATE USER "etherdb"@"localhost" identified by "etherdb";'
  - mysql -e "ALTER DATABASE etherdb CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;"
  - mysql -e "grant CREATE,ALTER,SELECT,INSERT,UPDATE,DELETE on etherdb.* to 'etherdb'@'localhost';"
  - mysql -e "CREATE TABLE \`store\` (\`key\` varchar(100) COLLATE utf8mb4_bin NOT NULL DEFAULT '',\`value\` longtext COLLATE utf8mb4_bin NOT NULL,PRIMARY KEY (\`key\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;" etherdb
# Brings in procedure required for creating large data set
  - mysql etherdb < test/lib/mysql.sql
  - mysql etherdb -e 'CALL generate_data();';
  - psql -c 'create database etherdb;' -U postgres
#  - psql -c "grant CREATE,ALTER,SELECT,INSERT,UPDATE,DELETE on etherdb.* to 'etherdb'@'localhost';" -U postgres
  - mongo etherdb --eval 'db.createUser({user:"etherdb",pwd:"test",roles:["readWrite"]});'

install:
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"

jobs:
  include:
    - name: "Run the Backend tests"
      install:
        - "npm install"

notifications:
  email:
    - john@mclear.co.uk
