language: node_js

node_js:
  - "lts/*"

services:
  - docker
  - mongodb
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE ueberdb;'
  - mysql -e 'CREATE USER "ueberdb"@"localhost" identified by "ueberdb";'
  - mysql -e "grant CREATE,ALTER,SELECT,INSERT,UPDATE,DELETE on ueberdb.* to 'ueberdb'@'localhost';"
  - mysql -e 'CREATE TABLE "store" ("key" varchar(100) COLLATE utf8mb4_bin NOT NULL DEFAULT "", "value" longtext COLLATE utf8mb4_bin NOT NULL, PRIMARY KEY ("key")) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;" ueberdb'
  - psql -c 'create database ueberdb;' -U postgres
#  - psql -c "grant CREATE,ALTER,SELECT,INSERT,UPDATE,DELETE on ueberdb.* to 'ueberdb'@'localhost';" -U postgres
  - mongo ueberdb --eval 'db.createUser({user:"ueberdb",pwd:"test",roles:["readWrite"]});'

install:
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"

jobs:
  include:
    - name: "Run the Backend tests"
      install:
        - "npm install"

notifications:
  email:
    - john@mclear.co.uk
